version: "3"

services:
  session_db1:
    container_name: session_db1
    image: mongo
    
  booking_db1:
    container_name: booking_db1
    image: mongo
    
  customer_db1:
    container_name: customer_db1
    image: mongo
    net: ${NETWORK}
    
  flight_db1:
    container_name: flight_db1
    image: mongo
  
  nginx1:
    container_name: nginx1
    net: ${NETWORK}
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/public
  
  main_service_liberty1:
    container_name: main_service_liberty1
    build: ./acmeair-mainapp/
    environment:
      - LICENSE=accept
  
  auth_service_liberty1:
    container_name: auth_service_liberty1
    build: ./acmeair-as/
    environment:
      - LICENSE=accept
  
  booking_service_liberty1:
    container_name: booking_service_liberty1
    build: ./acmeair-bs/
    environment:
      - LICENSE=accept
  
  customer_service_liberty1:
    container_name: customer_service_liberty1
    build: ./acmeair-cs/
    environment:
      - LICENSE=accept
  
  flight_service_liberty1:
    container_name: flight_service_liberty1
    build: ./acmeair-fs/
    environment:
      - LICENSE=accept
  
  support_service_liberty1:
    container_name: support_service_liberty1
    build: ./acmeair-ss
    environment:
      - LICENSE=accept
