apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.bookingService.name }} 
  name: {{ .Values.bookingService.name }} 
spec:
  ports:
  - port: {{ .Values.bookingService.port }} 
  selector:
    service: {{ .Values.bookingService.name }} 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /acmeair-bs
  name: booking-ingress
spec:
  rules:
  - host: {{ .Values.bookingIngress.host }}  
    http:
      paths:
      - path: /booking/acmeair-bs
        backend:
          serviceName: {{ .Values.bookingService.name }} 
          servicePort: {{ .Values.bookingService.port }} 
